<head>
    <meta charset="UTF-8"> 
    <meta name="Community Organisation" content="width=device-width, initial-scale=1.0">
    <title>Community Organisation</title>
    <link rel="stylesheet" type="text/css" href="../css/style.css">
    <script src="../js/script.js"></script>
</head>
<body>
    <header id="header">
        <div id="head">
            <p>Stick It In</p>
        </div>
	</header>
</body>
