<div class="navBar">
    <div class="col-md-12">
        <div class=".col-md-6 .col-md-offset-3">
            <div class="row">
                <div id="navigation">
                    <ul>
                        <div class="col-md-4 col-md-offset-4">
                            <li class="active"><a href="#">Home</a></li>
                            <li class="active"><a href="#">Events</a></li>
                            <li class="active"><a href="#">Contact</a></li>
                            <li class="active"><a href="#">About</a></li>
                        </div>
                        <div class="col-md-2 col-md-offset-2">
                            <li class="active"><a href="#">Login</a></li>
                            <li class="active"><a href="#">Register</a></li>
                        </div>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
